# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Docker Login
        env: 
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login --username rabbitoj --password-stdin

      - name: Github Package Login
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u ttzztztz --password-stdin

      - name: Get the TagName
        id: tag_name
        env:
          GITHUB_REF: ${{ github.ref }}
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)
      
      - name: "Fetch and build Tester v2"
        run: |
          git clone https://github.com/Rabbit-OJ/Rabbit-OJ-Tester-v2.git
          cd ./Rabbit-OJ-Tester-v2
          rustup target add x86_64-unknown-linux-musl
          cargo build --target x86_64-unknown-linux-musl --release
          cd ../
          cp ./Rabbit-OJ-Tester-v2/target/x86_64-unknown-linux-musl/release/Rabbit-OJ-Tester-v2 ./tester
          
      - name: "Build and Publish alpine-tester"
        env: 
          TAG_NAME: ${{ steps.tag_name.outputs.TAG }}
          TESTER_NAME: alpine_tester
        run: |
          docker build -f "./$TESTER_NAME/Dockerfile" -t "rabbitoj/$TESTER_NAME:$TAG_NAME" .
          docker push "rabbitoj/$TESTER_NAME:$TAG_NAME"
          docker tag "rabbitoj/$TESTER_NAME:$TAG_NAME" "docker.pkg.github.com/rabbit-oj/Dockerfiles/$TESTER_NAME:$TAG_NAME"
          docker push "docker.pkg.github.com/rabbit-oj/Dockerfiles/$TESTER_NAME:$TAG_NAME"

      - name: "Build and Publish java-tester"
        env: 
          TAG_NAME: ${{ steps.tag_name.outputs.TAG }}
          TESTER_NAME: java_tester
        run: |
          docker build -f "./$TESTER_NAME/Dockerfile" -t "rabbitoj/$TESTER_NAME:$TAG_NAME" .
          docker push "rabbitoj/$TESTER_NAME:$TAG_NAME"
          docker tag "rabbitoj/$TESTER_NAME:$TAG_NAME" "docker.pkg.github.com/rabbit-oj/Dockerfiles/$TESTER_NAME:$TAG_NAME"
          docker push "docker.pkg.github.com/rabbit-oj/Dockerfiles/$TESTER_NAME:$TAG_NAME"

      - name: "Build and Publish node-tester"
        env: 
          TAG_NAME: ${{ steps.tag_name.outputs.TAG }}
          TESTER_NAME: node_tester
        run: |
          docker build -f "./$TESTER_NAME/Dockerfile" -t "rabbitoj/$TESTER_NAME:$TAG_NAME" .
          docker push "rabbitoj/$TESTER_NAME:$TAG_NAME"
          docker tag "rabbitoj/$TESTER_NAME:$TAG_NAME" "docker.pkg.github.com/rabbit-oj/Dockerfiles/$TESTER_NAME:$TAG_NAME"
          docker push "docker.pkg.github.com/rabbit-oj/Dockerfiles/$TESTER_NAME:$TAG_NAME"

      - name: "Build and Publish python-tester"
        env: 
          TAG_NAME: ${{ steps.tag_name.outputs.TAG }}
          TESTER_NAME: python_tester
        run: |
          docker build -f "./$TESTER_NAME/Dockerfile" -t "rabbitoj/$TESTER_NAME:$TAG_NAME" .
          docker push "rabbitoj/$TESTER_NAME:$TAG_NAME"
          docker tag "rabbitoj/$TESTER_NAME:$TAG_NAME" "docker.pkg.github.com/rabbit-oj/Dockerfiles/$TESTER_NAME:$TAG_NAME"
          docker push "docker.pkg.github.com/rabbit-oj/Dockerfiles/$TESTER_NAME:$TAG_NAME"

      - name: "Build and Publish swift-tester"
        env: 
          TAG_NAME: ${{ steps.tag_name.outputs.TAG }}
          TESTER_NAME: swift_tester
        run: |
          docker build -f "./$TESTER_NAME/Dockerfile" -t "rabbitoj/$TESTER_NAME:$TAG_NAME" .
          docker push "rabbitoj/$TESTER_NAME:$TAG_NAME"
          docker tag "rabbitoj/$TESTER_NAME:$TAG_NAME" "docker.pkg.github.com/rabbit-oj/Dockerfiles/$TESTER_NAME:$TAG_NAME"
          docker push "docker.pkg.github.com/rabbit-oj/Dockerfiles/$TESTER_NAME:$TAG_NAME"
